#!/bin/bash

process=`ps -e f | grep --color=never "https://stream.radiojar.com/8s5u5tpdtwzuv" | grep --color=never mpv | awk '{print $1}'`

case $1 in
    "play")
        if [ -z $process ]; then
            eww update quran_button="1" 
            mpv https://stream.radiojar.com/8s5u5tpdtwzuv
        else
            dunstify "EWW: Cairo Quran CONFLICT!" "\nThere's already a process running"
        fi
        ;;
    "stop")
        if [ -z $process ]; then
            dunstify "EWW: Cairo Quran NOT RUNNING!" "\nNo process is running to be stopped"
        else
            eww update quran_button="0"
            kill $process
        fi
        ;;
    *)
        dunstify "EWW: Cairo Quran ERROR!" "\n'$1': INVALID ARGUMENT\n\nEither 'play' or 'stop' were expected"
        ;;
esac
