#!/bin/bash

source ~/.scripts/cmdfns

choice=`cliphist list | fzfcmd --ansi \
                     -d $'\t' \
                     --with-nth 2 \
                     --prompt='Clip > ' \
                     --preview-window=right:50% \
                     --preview='~/.scripts/files/clip-preview {}'`

[ -n "$choice" ] && printf $choice | cliphist decode | wl-copy
