#!/bin/bash

choice=`cat ~/.scripts/files/scriptman-list |\
     awk -F ';' '{ printf "%2s %-5s %s\n", " ", $1, $2}' |\
     fzf --color=pointer:1,prompt:4,hl:4,bg+:'#45403d',fg+:7,hl+:1 --prompt='CMD > ' |\
     sed 's/[^A-Za-z]/ /g; s/ \{3,\}//g'`

if [ -n "$choice" ]; then
    cmd=`cat ~/.scripts/files/scriptman-list |\
        grep --color=never -w ";$choice" |\
        awk -F ';' '{print $3}'`

    script=`echo "$cmd" |\
        cut -d' ' -f1`

    if [ -f ~/.scripts/$script ]; then
        bash -c "~/.scripts/$cmd"
    else
        bash -c "nohup bash -c '$cmd &' 2&>1"
    fi
fi
