#!/bin/bash

wallpaper="`ls -l --color=never ~/Pictures/wallpapers/ | awk '{print $9}' | sed '/^$/d' | shuf -n 1`"

pkill lxpolkit
pkill eww
pkill dunst
pkill foot
pkill gammastep
pkill kdeconnectd
pkill swww-daemon
pkill wl-paste
pkill pipewire
pkill pipewire-pulse
pkill wireplumber

swww-daemon --format xrgb &
swww img ~/Pictures/wallpapers/"$wallpaper" &
dunst &
lxpolkit &
foot -s &
gammastep -O 3500 &
/usr/lib/kdeconnectd &
fcitx5 -d --replace &
eww open bar &
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
wl-paste --primary --watch cliphist store &
pipewire &
pipewire-pulse &
wireplumber &

#swaybg -m fill -i ~/Pictures/wallpapers/"$wallpaper" &
