#!/bin/bash

wallpaper="`ls -l --color=never ~/Pictures/wallpapers/ | awk '{print $9}' | sed '/^$/d' | shuf -n 1`"

cleaner=("lxpolkit" "kdeconnect-indicator" "eww" "dunst" "gammastep" "kdeconnectd" "swww-daemon" "wl-paste" "pipewire" "pipewire-pulse" "wireplumber" "fcitx5")

for str in ${cleaner[@]}; do
    kill -SIGTERM `pgrep $str`
done

swww-daemon --format xrgb &
swww img ~/Pictures/wallpapers/"$wallpaper" &
dunst &
lxpolkit &
gammastep -O 3500 &
/usr/lib/kdeconnectd &
fcitx5 -d --replace &
eww open bar &
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
wl-paste --primary --watch cliphist store &
pipewire &
pipewire-pulse &
wireplumber &
kdeconnect-indicator &
~/.scripts/detect_headphone &
~/.scripts/ytrss update
