#!/bin/bash

function fzfcmd { 
    fzf --color=preview-bg:'#282829',pointer:1,prompt:4,hl:4,bg+:'#45403d',fg+:7,hl+:1 \
        --bind 'tab:toggle+up,shift-tab:toggle+down' \
        --tiebreak=begin \
        "$@"
}

function notifier { 
    case $1 in
        normal) notify-send -i "$2" "$3" "\n<b><u>$4</u></b>\n\n${@:5}"  ;;
        err) notify-send -i "$2" "$3" "\n<b>'$4': <u>Invalid argument</u></b>\n\n${@:5}" ;;
        add) notify-send -i "$2" "$3" "\n<b><u>Added successfully</u></b>\n\n${@:4}" ;;
    esac
}

function fzfprompt {
    echo "" |\
        fzf --print-query -0 \
            --color=pointer:0,prompt:4,hl:4,bg+:0,fg+:7,hl+:1 \
            --header="" \
            --no-info \
            --prompt="$1 > " \
            "${@:2}" | sed '/^$/d'
}

function mpvcmd {
    notifier normal \
        "im-youtube" \
        "Mpv (mpvcmd)" \
        "Your video will run shortly"

    mpv --ytdl=yes \
        --cache=yes \
        --cache-secs=30 \
        --script-opts=ytdl_hook-ytdl_path=yt-dlp \
        --ytdl-raw-options=force-ipv4= \
        --ytdl-format='bestvideo[ext=mp4][vcodec^=avc][height<=720]+bestaudio/best[height<=720]' \
        "$@"

    if [[ $? != 0 ]]; then
        notifier normal \
            "dialog-error" \
            "Mpv (mpvcmd)" \
            "mpv (yt-dlp) failed to run url" \
            "<b>Make sure it can be handled by yt-dlp</b>"
    fi
}

function ytrssCheckUrl {
    case $1 in
        add)
            if grep -q -w "^$2$" ~/.scripts/data/ytsubs; then
                notifier normal \
                "dialog-error" \
                "Ytrss" \
                "Feed already exists"
            else
                echo "$2" >> ~/.scripts/data/ytsubs
                notifier normal \
                "application-rss+xml" \
                "Ytrss" \
                "Feed added successfully" \
                "<b>$3</b>"
            fi
            ;;
        import)
            if ! grep -q -w "^$2$" ~/.scripts/data/ytsubs; then
                echo "$2" >> ~/.scripts/data/ytsubs
            fi
            ;;
    esac
}
