#!/bin/sh
# These bastards hog all the cpu uselessly ... after some search, I finally found how to disable them.
# 
# You will see many of them hanging around after running the following command to find the interrupts
# `grep . --color=never -r /sys/firmware/acpi/interrupts`
# 
# Don't try to disable them all because you can't. it will tell you that
# `echo: write error: Invalid argument`
#
# The only ones worked with me are non-'invalid'...
# `grep . --color=never -r /sys/firmware/acpi/interrupts | sed '/invalid/d'`
# 
# The remaining ones are the ones you should disable and/or mask them as you can.
#
# These are the ones I disabled on my system (HP Pavilion g6) running Arch linux
#
# I Ended up putting this in a root crontab
# `sudo -s`
# `EDITOR=nvim crontab -e`
#
# REMEMBER THE FORMAT!
# `@reboot echo ...`

# DISABLED
sudo echo "disable" > /sys/firmware/acpi/interrupts/sci
sudo echo "disable" > /sys/firmware/acpi/interrupts/gpe1D
sudo echo "disable" > /sys/firmware/acpi/interrupts/gpe1F
sudo echo "disable" > /sys/firmware/acpi/interrupts/ff_gbl_lock 
sudo echo "disable" > /sys/firmware/acpi/interrupts/gpe06
sudo echo "disable" > /sys/firmware/acpi/interrupts/gpe02
sudo echo "disable" > /sys/firmware/acpi/interrupts/gpe01
sudo echo "disable" > /sys/firmware/acpi/interrupts/ff_pwr_btn
sudo echo "disable" > /sys/firmware/acpi/interrupts/gpe07

# MASKED
sudo echo "mask" > /sys/firmware/acpi/interrupts/gpe1D
sudo echo "mask" > /sys/firmware/acpi/interrupts/sci
sudo echo "mask" > /sys/firmware/acpi/interrupts/gpe07
sudo echo "mask" > /sys/firmware/acpi/interrupts/gpe0D
sudo echo "mask" > /sys/firmware/acpi/interrupts/gpe01
sudo echo "mask" > /sys/firmware/acpi/interrupts/gpe06
sudo echo "mask" > /sys/firmware/acpi/interrupts/gpe02
sudo echo "mask" > /sys/firmware/acpi/interrupts/gpe07
