#!/bin/bash

source ~/.scripts/extra/cmdfns

[ ! -f ~/.scripts/data/.web_bookmarks ] && touch ~/.scripts/data/.web_bookmarks

case $1 in
    "add")
        bookmark=`wl-paste`
        if [[ $bookmark =~ ^"http" ]]; then
            if grep -q "$bookmark" ~/.scripts/data/.web_bookmarks ;then
                notifier normal \
                    "bookmarks" \
                    "Bookmark" \
                    "Already exists"
            else
                name=`fzfprompt "Bookmark Name" --header="$bookmark"`
                if [ -n "$name" ]; then
                    notifier add \
                        "bookmark-new" \
                        "Bookmark" \
                        "<b>$name</b>\n\n<b>$bookmark</b>"

                    echo -e "$name;;;$bookmark" >> ~/.scripts/data/.web_bookmarks
                else
                    notifier normal \
                        "bookmarks" \
                        "Bookmark" \
                        "Not saved because you didn't specify a name"
                fi
            fi
        else
            notifier normal \
                "dialog-error" \
                "Bookmark" \
                "Text in your clipboard is not a valid url"
        fi
        ;;
    
    "query")
        query=`cat ~/.scripts/data/.web_bookmarks |\
            awk -F ';;;' '{ printf "%2s %-40s %s\n", " ", $1, $2}' |\
            fzfcmd --prompt='Bookmarks > ' |\
            sed 's/^.*http/http/g'`

        if [ -n "$query" ]; then
            printf "$query" | wl-copy
        fi
        ;;

    "rename")
        query=`cat ~/.scripts/data/.web_bookmarks |\
            awk -F ';;;' '{ printf "%2s %-40s %s\n", " ", $1, $2}' |\
            fzfcmd --prompt='Bookmarks > ' |\
            sed 's/^.*http/http/g'`

        if [ -n "$query" ]; then
            rename=`fzfprompt "Bookmark Rename" --header="$query"`

            if [ -n "$rename" ]; then
                notifier normal \
                    "edit" \
                    "Bookmark" \
                    "Bookmark name has changed to" \
                    "<b>$rename</b>\n\n<b>$query</b>"

                printf "$query" |\
                    xargs -n 1 -I {} sed -i "s|^.*;;;{}$|$rename;;;{}|g" ~/.scripts/data/.web_bookmarks 2&>/dev/null
            else
                notifier normal \
                    "bookmarks" \
                    "Bookmark" \
                    "Bookmark hasn't been named because valid input was not provided"
            fi
        fi
        ;;

    "delete")
        del=`cat ~/.scripts/data/.web_bookmarks |\
            awk -F ';;;' '{ printf "%2s %-30s %s\n", " ", $1, $2}' |\
            fzfcmd --multi --prompt='Delete Bookmark > ' |\
            sed 's/^.*http/http/g'`

        if [ -n "$del" ]; then
            echo "$del" |\
                xargs -n 1 -I {} sed -i "\|;;;{}$|d" ~/.scripts/data/.web_bookmarks 2&>/dev/null
        fi
            
        ;;

    *)
        notifier err \
            "dialog-error" \
            "Bookmark" \
            $1 \
            "Either 'add' or 'query' were expected"
        ;;
esac
