#!/bin/bash

choice=$(cat ~/.scripts/files/browser-list |\
            awk -F ';' '{ printf "%2s %-4s %s\n", " ", $1, $2}' |\
            fzf --color=pointer:1,prompt:4,hl:4,bg+:'#45403d',fg+:7,hl+:1 --prompt='Firefox > ' |\
            sed 's/[^A-Za-z0-9]/ /g; s/ \{3,\}//g')

if [ -n "$choice" ]; then
    nohup bash -c "firefox -P $choice &" 2&>1
fi
