#!/bin/sh

choice=$(cat ~/.scripts/files/browser-list | awk -F ';' '{ printf "%-4s %-40s\n", $1, $2}' | tofi --config ~/.scripts/configs/tofi.cfg | sed 's/^.\s\s\s\s//g')

if ! [ -z $choice ]; then
    firefox -P $choice
fi
