#!/bin/bash

case $1 in
    "query")
        choice=`cliphist list | tofi --config ~/.scripts/configs/tofi-top.cfg --prompt-text=" clip  "`
        if [ -n "$choice" ]; then
            printf $choice | cliphist decode | wl-copy
        else
            notify-send "Clipboard" "\n<u><b>No item valid item selected, so will not copy</b></u>"
        fi
    ;;
    
    "delete")
        choice=`cliphist list | tofi --config ~/.scripts/configs/tofi-top.cfg --prompt-text=" clip  " --selection-background="ea6962"`
        if [ -n "$choice" ]; then
            printf $choice | cliphist delete 
        else
            notify-send "Clipboard" "\n<u><b>No item valid item selected, so will not copy</b></u>"
        fi
    ;;
    *)
        notify-send "Clipboard" "\n<u>'$1': <b>Invalid argument</b></u>\n\n<b>Either 'query' or 'delete' were expected</b>"
    ;;
esac
