#!/bin/bash

function fzfcmd { 
    fzf --color=preview-bg:'#282829',pointer:1,prompt:4,hl:4,bg+:'#45403d',fg+:7,hl+:1 \
        --bind 'tab:toggle+up,shift-tab:toggle+down' \
        --tiebreak=begin \
        "$@"
}

function notifier { 
    case $1 in
        normal) notify-send -i "$2" "$3" "\n<b><u>$4</u></b>\n\n${@:5}"  ;;
        err) notify-send -i "$2" "$3" "\n<b>'$4': <u>Invalid argument</u></b>\n\n${@:5}" ;;
        add) notify-send -i "$2" "$3" "\n<b><u>Added successfully</u></b>\n\n${@:4}" ;;
    esac
}

function fzfprompt {
    echo "" |\
        fzf --print-query -0 \
            --color=pointer:0,prompt:4,hl:4,bg+:0,fg+:7,hl+:1 \
            --header="" \
            --no-info \
            --prompt="$1 > " \
            "${@:2}" | sed '/^$/d'
}

function mpvcmd {
    mpv --ytdl=yes \
        --ytdl-raw-options=force-ipv4= \
        --ytdl-format='bestvideo[height<=480]+bestaudio/best[height<=480]' \
        "$@"
}
