#!/bin/bash

# Using console because of both sixel and bidi are available
function floating () { konsole --notransparency --profile Floating -e "$@"; }

# Using mlterm because fzf previews overlap in konsole :(
function fclip () { mlterm --title="Floating" -e "$@"; }


case $1 in
    sman) floating ~/.scripts/files/scriptfzf;;
    clip) fclip ~/.scripts/files/lsclip;;
    run) floating ~/.scripts/cmdrunner;;
    mark) floating ~/.scripts/bookmark query;;
    addmark) floating ~/.scripts/bookmark add;;
    delmark) floating ~/.scripts/bookmark delete;;
    ffprofile) floating ~/.scripts/browser;;
    search) floating ~/.scripts/search;;
    ytrss) floating ~/.scripts/ytrss view;;
    rename) floating ~/.scripts/rename ${@:2};;
esac
