#!/bin/bash

# Using console because both sixel and bidi are available
function floating () { konsole --notransparency -p tabtitle="Floating" -e "$@"; }


case $1 in
    sman) floating ~/.scripts/files/scriptfzf;;
    clip) floating ~/.scripts/files/lsclip;;
    run) floating ~/.scripts/cmdrunner;;
    mark) floating ~/.scripts/bookmark query;;
    ffprofile) floating ~/.scripts/browser;;
    search) floating ~/.scripts/search;;
    ytrss) floating ~/.scripts/ytrss view;;
    rename) floating ~/.scripts/rename ${@:2};;
esac
