#!/bin/bash

source ~/.scripts/extra/cmdfns

case $1 in 
    name)
        font=`fc-list |\
                awk -F ":" '{print $2}' |\
                sed 's/,.*$//g' |\
                sort -u |\
                fzfcmd --prompt "Font > "`

        if [ -n "$font" ]; then
            printf "$font" | wl-copy
            
            notifier normal \
                "dialog-text-and-font" \
                "Fontmenu" \
                "Font copied to clipboard"
        fi
        ;;

    file)
        font=`fc-list |\
            awk -F ":" '{print $1}' |\
            awk -F "/" '{print $NF}' |\
            sort -u |\
            fzfcmd --prompt "Font file > "`

        if [ -n "$font" ]; then
            printf "$font" | wl-copy
            
            notifier normal \
                "dialog-text-and-font" \
                "Fontmenu" \
                "Font filename copied to clipboard"
        fi
        ;;
    *)
        notifier err \
            "dialog-error" \
            "Fontmenu" \
            "$1" \
            "Either 'name' or 'file' were expected"
        ;;
esac

