#!/bin/sh

BG='#282828'
alphaBG='#28282855'
TEXT='#d4be98'
YELLOW='#fabd2f'
RED='#ea6962'
BLUE='#7daea3'
GREEN='#a9b665'

swaylock \
--image "~/Pictures/wallpapers/ign_desert.png" \
--effect-blur=2x2 \
--indicator-x-position 150 \
--indicator-y-position 650 \
--scaling=fill \
--indicator				\
--indicator-thickness=15		\
--font-size=50				\
--indicator-radius 50			\
--text-wrong=""			\
--text-ver=""			\
--text-clear=""         \
--color=$BG				\
--key-hl-color=$YELLOW			\
--bs-hl-color=$YELLOW			\
--separator-color=$YELLOW		\
--line-color=$BG  		        \
--line-clear-color=$BG  		\
--line-wrong-color=$BG  		\
--line-ver-color=$BG  			\
--layout-bg-color=$BG 			\
--layout-text-color=$TEXT 		\
--inside-color=$alphaBG			\
--inside-ver-color=$alphaBG			\
--inside-clear-color=$alphaBG		\
--inside-wrong-color=$alphaBG		\
--ring-color=$RED			\
--ring-ver-color=$BLUE			\
--ring-wrong-color=$YELLOW		\
--ring-clear-color=$GREEN
