#!/bin/bash

source ~/.scripts/cmdfns

url=`fzfprompt "MPV YT"`

if [ -n "$url" ]; then
    if [[ $url =~ ^"https" ]]; then
        nohup bash -c "mpv --ytdl=yes \
            --ytdl-raw-options=force-ipv4= \
            --ytdl-format='bestvideo[height<=480]+bestaudio/best[height<=480]' \
            $url &" 2&>1
    else
        dunstify "MPV YT ERROR!" "\nYou have provided an invalid URL\n\nMake sure it's a Youtube URL"
    fi
fi
