#!/bin/bash

url=`echo "" |\
    fzf --print-query -0 \
        --color=pointer:0,prompt:4,hl:4,bg+:0,fg+:7,hl+:1 \
        --header="" \
        --no-info \
        --prompt='MPV YT > ' | sed '/^$/d'`

if [ -n "$url" ]; then
    if [[ $url =~ ^"https" ]]; then
        nohup bash -c "mpv --ytdl=yes \
            --ytdl-raw-options=force-ipv4= \
            --ytdl-format='bestvideo[height<=480]+bestaudio/best[height<=480]' \
            $url &" 2&>1
    else
        dunstify "MPV YT ERROR!" "\nYou have provided an invalid URL\n\nMake sure it's a Youtube URL"
    fi
fi
