#!/bin/bash

source ~/.scripts/extra/cmdfns

case $1 in
    "install")
        curl \
            'https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/css/nerd-fonts-generated.css' \
            -o ~/.scripts/nerd-fonts-generated.css

        cat nerd-fonts-generated.css |\
            grep --color=never -A 2 "nf-" |\
            sed 's/^\.//g; s/:before {//g; s/  content: "//g; s/";$//g; /^}$/d; s/\\/\\U/g' |\
            paste -sd ' \n' |\
            awk '{print $2";;;"$1}' > ~/.scripts/data/nerd-icons

        ;;

    "query")
        icon=`printf "$(cat ~/.scripts/data/nerd-icons)" |\
                awk -F ';;;' '{ printf "%2s %-5s %s\n", " ", $1, $2}' |\
                fzfcmd --prompt='Nerd > ' |\
                awk '{print $1}'`

        [ -n "$icon" ] && wl-copy "$icon"
        ;;

    *)
        notifier err \
            "dialog-error" \
            "Nerdmenu" \
            "$1" \
            "<b>Either 'install' or 'query' was expected</b>"
        ;;
esac
