#!/bin/bash
choice=$( cat ~/.scripts/files/power-list | column -s ";" -t | tofi --config ~/.scripts/configs/tofi.cfg --prompt-text=" " | sed 's/^.*\s\s//g')

case $choice in
    "poweroff")
        doas poweroff;;
    "reboot")
        doas reboot;;
    "logout")
        pkill river;;
    "suspend")
        bash ~/.scripts/lock & sleep 1 && doas zzz ;;
    "sleep")
        doas zzz;;
    "lock screen")
        bash ~/.scripts/lock;;
    *)
        echo "invalid choice";;
esac
