#!/bin/bash

# Just supply the url from the button in https://prayerwebcal.dsultan.com/
# after configuring the settings as first argument and it will output 
# the result in the same directory you invoked the script from.
#
# the resulted file is expected to be placed in ~/.config/eww/scripts 
# unless you changed eww configuration.

url="$1"

if [ -z "$url" ]; then
    notify-send "Prayer-ical-parser" "\n<b>'$1'<u>Invalid argument</u><b>\n\n<b>Please supply the webcal url as an argument</b>"
else
    echo "$url" | sed 's/^webcal/https/g' | xargs curl | grep --color=never -C 1 --no-group-separator "DTEND" | sed '/DTEND/d; s/:.*Sunrise/:Sunrise/; s/\r//g;' | awk -F ':' '{print $2}' | sed 'N;s/\n/\t/g; s/^[0-9]\{4\}//g' > ~/.config/eww/scripts/prayers
    notify-send "Prayer-ical-parser" "\n<b><u>Output successfully saved</u></b>\n\n~/.config/eww/scripts/prayers"
fi
