#!/bin/bash

source ~/.scripts/cmdfns

choice=`cat ~/.scripts/files/search-list |\
     awk -F ';' '{ printf "%2s %-5s %-5s %s\n", " ", $1, $2, $3}' |\
     fzfcmd --tiebreak=begin --prompt='Search > '`

if [ -n "$choice" ]; then
    entry=`echo $choice | sed 's/\s/;/; s/\s/;/'`
    url=`grep -w "$entry" ~/.scripts/files/search-list | awk -F ';' '{print $4}'`
    prompt=`grep -w "$entry" ~/.scripts/files/search-list | awk -F ';' '{print $3}'`

    input=`fzfprompt "$prompt"`

    if [ -n "$input" ]; then
        nohup bash -c "firefox \"${url}$input\" &" 2&>/dev/null
    fi
fi
