#!/bin/bash

source ~/.scripts/cmdfns

choice=`cat ~/.scripts/files/search-list |\
     awk -F ';' '{ printf "%2s %-5s %s\n", " ", $1, $2}' |\
     fzfcmd --prompt='Search > ' |\
     sed 's/[^A-Za-z]/ /g; s/ \{3,\}//g'`

if [ -n "$choice" ]; then
    url=`grep ";$choice;" ~/.scripts/files/search-list | sed "s/^.*;$choice;//g"`

    input=`fzfprompt "$choice"`

    if [ -n "$input" ]; then
        nohup bash -c "firefox \"${url}$input\" &" 2&>1
    fi
fi
