#!/bin/bash

step=5

muted=`pamixer --get-mute`

case $1 in
    "down")
        if [ $muted == "false" ]; then 
		    pamixer -d $step
            volume=`pamixer --get-volume`
            eww update volume="$volume"
	    fi
        ;;
    "up")
        if [ $muted == "false" ]; then
		    pamixer -i $step
            volume=`pamixer --get-volume`
            eww update volume="$volume"
	    fi
        ;;
    "toggle")
	    pamixer -t
        muted=`pamixer --get-mute`
        volume=`pamixer --get-volume`
        eww update volume_mute="$muted"
        ;;
    *)
        echo "Invalid option"
        ;;
esac


if [ $muted == "true" ]; then
    notify-send -r 5501232 "Muted" -t 2000 -i audio-volume-muted
else
    notify-send -r 5501232 "Volume  $volume%" -t 2000 -i audio-volume-high -h int:value:$volume
fi

