#!/bin/bash

step=5

muted=`pamixer --get-mute`

case $1 in
    "down")
        if [ $muted == "false" ]; then 
		    pamixer -d $step
	    fi
        ;;
    "up")
        if [ $muted == "false" ]; then
		    pamixer -i $step
	    fi
        ;;
    "toggle")
	    pamixer -t
        ;;
    *)
        echo "Invalid option"
        ;;
esac

volume=`pamixer --get-volume`
muted=`pamixer --get-mute`

if [ $muted == "true" ]; then
    dunstify -r 5501232 "Muted" -t 2000 -i audio-volume-muted
else
    dunstify -r 5501232 "Volume  $volume%" -t 2000 -i audio-volume-high -h int:value:$volume
fi

