#!/bin/bash

source ~/.scripts/cmdfns

function updater {
    while IFS="" read -r yturl || [ -n "$yturl" ]
    do
    # RSSURL
    rssUrl=`curl -s "$yturl" | grep '"rssUrl":' | sed 's/^.*"rssUrl"://g; s/",".*$//g; s/.*http/http/g'`

    # Filter
    #sed 'N;N;N;N;s/\n/;;;/g; s/;;; $//g' |\
    curl -s "$rssUrl" |\
            sed '/<media:description>/,/<\/media:description/d; /<media:community>/,/<\/media:community>/d; /<author>/,/<\/author>/d; /<updated>/d; /<media:content/d; /<yt:channelId>/d; /<yt:videoId>/d; /<id>/d; /<media:title>/d; /media:group>/d;' |\
            awk '/<entry>/,/<\/entry>/' |\
            sed 's/^.*<media:thumbnail url="//g; s/^.*href="//g; s/".*$//g; s/^.*<title>//g; s/<\/title>//g; /<entry>/d; s/<\/entry>//g; s/^.*<published>//g; s/<\/published>//g' |\
            perl -pe 's/\n/;;;/g if $. % 5' |\
            sed 's/&quot;/"/g' |\
            awk -F ';;;' '{t=$1; $1=$3; $3=t; print $1";;;"$2";;;"$3";;;"$4 ;}' >> ~/.cache/boatcfg/scripts/ytrss
    done < ~/.scripts/files/ytsubs
}

case $1 in
    view)
        if ! [ -f ~/.cache/boatcfg/scripts/ytrss ]; then
            clear
            echo "Updating feed..."
            updater
        fi

        choice=`cat ~/.cache/boatcfg/scripts/ytrss |\
            sort -r |\
            awk -F ';;;' '{ printf "%s\n", $3}' |\
            fzfcmd --preview-window=right:55% \
                   --preview="~/.scripts/files/ytrss-preview {}"`

        choiceUrl=`grep ";;;$choice" ~/.cache/boatcfg/scripts/ytrss | awk -F ';;;' '{print $2}'`

        if [ -n "$choice" ]; then
            nohup bash -c "mpv --ytdl=yes \
                --ytdl-raw-options=force-ipv4= \
                --ytdl-format='bestvideo[height<=720]+bestaudio/best[height<=720]' \
                $choiceUrl &" 2&>/dev/null
        fi
        ;;

    update)
        rm ~/.cache/boatcfg/scripts/ytrss
        updater
        ;;

    *)
        ;;
esac
