#!/bin/bash

source ~/.scripts/extra/cmdfns
    
if ! [ -f ~/.scripts/data/ytsubs ]; then
    touch ~/.scripts/data/ytsubs
fi

function updater {
    if ! [ -f ~/.cache/boatcfg/scripts/tmp ]; then
        mkdir -p ~/.cache/boatcfg/scripts/tmp
    fi
    
    rm ~/.cache/boatcfg/scripts/tmp/*

    cat ~/.scripts/data/ytsubs |\
        awk -F ';;;' '{print $2}' |\
        sed 's/=/={/g; s/$/}/g' |\
        xargs -P 0 -I {} curl -s {} --output ~/.cache/boatcfg/scripts/tmp/'#1'

    if [ $? -ne 0 ]; then
        notifier normal \
                 "dialog-error" \
                 "Ytrss" \
                 "Cannot fetch feed, There seems to be a network error"
        exit 1
    fi

    cat ~/.cache/boatcfg/scripts/tmp/* |\
            awk '/<entry>/,/<\/entry>/' |\
            grep --no-group-separator --color=never -A 10 href |\
            sed '/author>/d; /<uri>/d; /<media:group>/d; /<media:content url=/d; /<updated>/d; s/.*href="//g; s/.*<media:thumbnail url="//g; s/".*$//g; s/.*<published>//g; s/<\/published>.*$//g; s/^.*<media:title>//g; s/<\/media:title>.*$//g; s/&quot;/"/g; s/^.*<name>//g; s/<\/name>.*$//g; s/&amp;/\&/g' |\
            perl -pe 's/\n/;;;/g if $. % 5' |\
            awk -F ';;;' '{t=$1; $1=$3; $3=t; print $1";;;"$2";;;"$3";;;"$4";;;"$5 ;}' > ~/.cache/boatcfg/scripts/ytrss

    notifier normal \
        "application-rss+xml" \
        "Ytrss" \
        "Feed updated successfully"
}

case $1 in
    view)
        if ! [ -f ~/.cache/boatcfg/scripts/ytrss ]; then
            clear
            echo "Updating feed..."
            updater
        fi

        choice=`cat ~/.cache/boatcfg/scripts/ytrss |\
            sort -r |\
            awk -F ';;;' '{ printf "%s\n", $4}' |\
            fzfcmd --preview-window=right:50% \
                   --preview="~/.scripts/data/ytrss-preview {}"`

        choiceUrl=`grep ";;;$choice" ~/.cache/boatcfg/scripts/ytrss | awk -F ';;;' '{print $3}'`

        if [ -n "$choice" ]; then
            nohup bash -c "source ~/.scripts/extra/cmdfns; mpvcmd $choiceUrl &" 2&>/dev/null
        fi
        ;;

    update)
        updater
        ;;

    add)
        yturl=`wl-paste`
        if [ -n "$yturl" ]; then
            if [[ $yturl =~ ^"https://www.youtube.com/" ]]; then
                rssinfo=`curl -s "$yturl" |\ 
                            grep '{"title":' |\
                            sed 's/.*{"channelMetadataRenderer"://g; s/{"title"://g; s/","description":.*,"rssUrl":"/;;;/g; s/",".*//g; s/^.*"//g; s/channel_id=UC/playlist_id=UU/g'`
                
                ytrssCheckUrl add $rssinfo $yturl
            else
                notifier normal \
                "dialog-error" \
                "Ytrss" \
                "Not a youtube url" \
                "<b>Please copy the url of a youtube channel to your clipboard</b>"
            fi
        fi
        ;;
    import)
        cat $2 |\
            jq ".subscriptions[] | .url, .name" |\
            sed 's|^"http.*channel/UC|https://www.youtube.com/feeds/videos.xml?playlist_id=UU|g; s/^"//g ;s/"$//g' |\
            perl -pe 's/\n/;;;/g if $. % 2' |\
            awk -F ';;;' '{t=$1; $1=$2; $2=t; print $1";;;"$2}' |\
            xargs -n1 -I {} bash -c 'source ~/.scripts/extra/cmdfns; ytrssCheckUrl import "{}"' 2&>/dev/null

        notifier normal \
            "application-rss+xml" \
            "Ytrss" \
            "Imported successfully"
        ;;
    *)
        notifier err \
            "dialog-error" \
            "Ytrss" \
            "$1" \
            "<b>One of 'view', 'update', 'add' or 'import' was expected</b>"
esac
