#!/bin/bash

# ----------------------------
# PACKAGE MANAGER
# ----------------------------
alias q='xbps-query -Rs'
alias u='doas xbps-install -Su'
alias i='doas xbps-install -S'
alias r='doas xbps-remove'


# ----------------------------
# TOOLS / UTILITIES
# ----------------------------
alias mki='make && doas make install'
alias grep='grep --color=always -i'
alias ll='eza -lah --icons=always'
alias v='nvim'
alias dv='doas nvim -u ~/.config/nvim/init.lua'
alias ugrub='doas grub-mkconfig -o /boot/grub/grub.cfg'
alias ytd='yt-dlp -f "bestvideo[height<=480]+bestaudio/best[height<=480]"'
alias sbrc="source ~/.bashrc"
alias rm="trash"
alias tl="trash-list"
alias tr="trash-restore"

# ----------------------------
# GIT
# ----------------------------

bare () {
    /usr/bin/git --git-dir=$HOME/git/boatcfg --work-tree=$HOME "$@"
}

alias ba="bare add"
alias bu="bare add -u"
alias bc="bare commit"
alias bp="bare push -u origin main"
alias bs="bare status"
alias bl="bare log"
alias blu="bare ls-files --others"
alias bpull="bare pull origin main --allow-unrelated-histories"
alias bds="bare diff --staged"
alias bd="bare diff"
alias br="bare rm"

alias gi='git init'
alias ga='git add'
alias gs='git status'
alias gl='git log'
alias gc='git commit'
alias gra='git remote set-url origin'
alias gp='git push -u origin main'
alias glu='git ls-files --others'
alias gpull='git pull origin main --allow-unrelated-histories'
alias gds="git diff --staged"
alias gd="git diff"
alias gr="git rm"

export PATH="$PATH:$HOME/.scripts:$HOME/go/bin"
export MANPAGER="nvim +Man!"
